### ISSUE TITLE
Telemetry screens not working

### ISSUE THREAD

**Issue by jcramer** [chsw/MavLink_FrSkySPort#24]
Hi chsw, 

I'm somewhat new to the taranisand Lua, and I've got this part way working on my system but I've hit a wall. I am running a Pixhawk and Taranis Plus. I am able to get the telemetry screens to display the arm status and the flight mode, that works well. However, I am not able to get any other information to the screens. I've spent a bit of time trying to get it to work and this is my last resort before I break down to understand your Lua scripts. I don't understand why it is only half working... Also I had thought the voltage was working at one point but now its just 0.0V....

I'd appreciate any help or direction.

Thank you, 
JIm

**Comment by chsw** [comment]
Have you checked your sr1_/sr2_ parameters? These parameters control the update interval for various parameters. 
If you haven't done so already, press the "enable telemetry"-button under Initial Setup->Optional Hardware->OSD in mission planner. This button will setup some of those parameters for you if I'm not mistaken. 

//Christian

**Comment by jcramer** [comment]
yep, that was my issue. Thank you for the help!
